{% set name = "proto-plus" %}
{% set version = "1.19.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/proto-plus-{{ version }}.tar.gz
  sha256: 4ca4055f7c5c1a2239ac7a12770a76a16269f58d3f01631523c20fc81dbb14a7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - protobuf >=3.19.0
    - python >=3.6

test:
  imports:
    - proto
    - proto.marshal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/proto-plus-python.git
  summary: Beautiful, Pythonic protocol buffers.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tswast
