{% set name = "proto-plus" %}
{% set version = "1.22.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/proto-plus-{{ version }}.tar.gz
  sha256: 0e8cda3d5a634d9895b75c573c9352c16486cb75deb0e078b5fda34db4243165

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - protobuf >=3.19.0,<5.0.0dev
    - python >=3.6

test:
  imports:
    - proto
    - proto.marshal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/proto-plus-python.git
  summary: Beautiful, Pythonic protocol buffers.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
    - tswast
