{% set name = "proto-plus" %}
{% set version = "1.18.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/proto-plus-{{ version }}.tar.gz
  sha256: bae25ef9e7d4290802d56ec81faba0a7cfe58843276eb15b320677b5b8b3f63d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - protobuf >=3.12.0
    - python

test:
  imports:
    - proto
    - proto.marshal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/proto-plus-python.git
  summary: Beautiful, Pythonic protocol buffers.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tswast
